//! The neutral DOCX house style, kept separate from the structural emitter.

/// Serif body (Georgia), the heading ladder, mono code, quote, footnotes,
/// hyperlinks, and the table grid.
pub(super) const STYLES_XML: &str = concat!(
    r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:"#,
    r#"w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">"#,
    r#"<w:docDefaults>"#,
    r#"<w:rPrDefault>"#,
    r#"<w:rPr>"#,
    r#"<w:rFonts w:ascii="Georgia" w:hAnsi="Georgia" w:cs="Georgia"/>"#,
    r#"<w:sz w:val="22"/>"#,
    r#"<w:szCs w:val="22"/>"#,
    r#"<w:lang w:val="en-US"/>"#,
    r#"</w:rPr>"#,
    r#"</w:rPrDefault>"#,
    r#"<w:pPrDefault>"#,
    r#"<w:pPr>"#,
    r#"<w:spacing w:after="160" w:line="300" w:lineRule="auto"/>"#,
    r#"</w:pPr>"#,
    r#"</w:pPrDefault>"#,
    r#"</w:docDefaults>"#,
    r#"<w:style w:type="paragraph" w:default="1" w:styleId="Normal">"#,
    r#"<w:name w:val="Normal"/>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="character" w:default="1" w:styleId="DefaultParagraphFon"#,
    r#"t">"#,
    r#"<w:name w:val="Default Paragraph Font"/>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading1">"#,
    r#"<w:name w:val="heading 1"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="240" w:after="120"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:sz w:val="40"/>"#,
    r#"<w:szCs w:val="40"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading2">"#,
    r#"<w:name w:val="heading 2"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="200" w:after="100"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:sz w:val="32"/>"#,
    r#"<w:szCs w:val="32"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading3">"#,
    r#"<w:name w:val="heading 3"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="180" w:after="80"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:sz w:val="28"/>"#,
    r#"<w:szCs w:val="28"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading4">"#,
    r#"<w:name w:val="heading 4"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="160" w:after="80"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:sz w:val="24"/>"#,
    r#"<w:szCs w:val="24"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading5">"#,
    r#"<w:name w:val="heading 5"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="160" w:after="80"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:sz w:val="22"/>"#,
    r#"<w:szCs w:val="22"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Heading6">"#,
    r#"<w:name w:val="heading 6"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepNext/>"#,
    r#"<w:spacing w:before="160" w:after="80"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:b/>"#,
    r#"<w:color w:val="666666"/>"#,
    r#"<w:sz w:val="22"/>"#,
    r#"<w:szCs w:val="22"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Quote">"#,
    r#"<w:name w:val="Quote"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:spacing w:before="120" w:after="120"/>"#,
    r#"<w:ind w:left="720"/>"#,
    r#"<w:pBdr>"#,
    r#"<w:left w:val="single" w:sz="18" w:space="8" w:color="D0D0D0"/>"#,
    r#"</w:pBdr>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:i/>"#,
    r#"<w:color w:val="5A5A5A"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="Code">"#,
    r#"<w:name w:val="Code Block"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:next w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:keepLines/>"#,
    r#"<w:spacing w:before="120" w:after="120" w:line="240" w:lineRule="auto"/>"#,
    r#"<w:ind w:left="120" w:right="120"/>"#,
    r#"<w:shd w:val="clear" w:color="auto" w:fill="F4F4F2"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:rFonts w:ascii="Consolas" w:hAnsi="Consolas" w:cs="Consolas"/>"#,
    r#"<w:sz w:val="20"/>"#,
    r#"<w:szCs w:val="20"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="ListParagraph">"#,
    r#"<w:name w:val="List Paragraph"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:spacing w:after="60"/>"#,
    r#"<w:contextualSpacing/>"#,
    r#"</w:pPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="TableCellText">"#,
    r#"<w:name w:val="Table Cell Text"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:spacing w:after="0" w:line="240" w:lineRule="auto"/>"#,
    r#"</w:pPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="paragraph" w:styleId="FootnoteText">"#,
    r#"<w:name w:val="Footnote Text"/>"#,
    r#"<w:basedOn w:val="Normal"/>"#,
    r#"<w:pPr>"#,
    r#"<w:spacing w:after="80" w:line="240" w:lineRule="auto"/>"#,
    r#"</w:pPr>"#,
    r#"<w:rPr>"#,
    r#"<w:sz w:val="19"/>"#,
    r#"<w:szCs w:val="19"/>"#,
    r#"<w:color w:val="666666"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="character" w:styleId="Hyperlink">"#,
    r#"<w:name w:val="Hyperlink"/>"#,
    r#"<w:basedOn w:val="DefaultParagraphFont"/>"#,
    r#"<w:rPr>"#,
    r#"<w:color w:val="2244AA"/>"#,
    r#"<w:u w:val="single"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="character" w:styleId="CodeChar">"#,
    r#"<w:name w:val="Code Char"/>"#,
    r#"<w:basedOn w:val="DefaultParagraphFont"/>"#,
    r#"<w:rPr>"#,
    r#"<w:rFonts w:ascii="Consolas" w:hAnsi="Consolas" w:cs="Consolas"/>"#,
    r#"<w:sz w:val="20"/>"#,
    r#"</w:rPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="table" w:default="1" w:styleId="TableNormal">"#,
    r#"<w:name w:val="Normal Table"/>"#,
    r#"<w:tblPr>"#,
    r#"<w:tblInd w:w="0" w:type="dxa"/>"#,
    r#"<w:tblCellMar>"#,
    r#"<w:top w:w="0" w:type="dxa"/>"#,
    r#"<w:left w:w="108" w:type="dxa"/>"#,
    r#"<w:bottom w:w="0" w:type="dxa"/>"#,
    r#"<w:right w:w="108" w:type="dxa"/>"#,
    r#"</w:tblCellMar>"#,
    r#"</w:tblPr>"#,
    r#"</w:style>"#,
    r#"<w:style w:type="table" w:styleId="TableGrid">"#,
    r#"<w:name w:val="Table Grid"/>"#,
    r#"<w:basedOn w:val="TableNormal"/>"#,
    r#"<w:tblPr>"#,
    r#"<w:tblBorders>"#,
    r#"<w:top w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"<w:left w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"<w:bottom w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"<w:right w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"<w:insideH w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"<w:insideV w:val="single" w:sz="4" w:space="0" w:color="AAAAAA"/>"#,
    r#"</w:tblBorders>"#,
    r#"</w:tblPr>"#,
    r#"</w:style>"#,
    r#"</w:styles>"#
);
