use super::Command;
use crate::keymap::Action;

pub(super) static COMMAND_SEED: &[Command] = &[
    Command {
        name: "Go to file…",
        action: Action::OpenGoto,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Switch project…",
        action: Action::OpenProject,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Recent projects…",
        action: Action::OpenRecentProjects,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Browse files…",
        action: Action::OpenBrowse,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Go to heading…",
        action: Action::OpenOutline,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Spell suggestions…",
        action: Action::OpenSpellSuggest,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Version history…",
        action: Action::OpenHistory,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Compare with version…",
        action: Action::CompareVersion,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Clean unused assets…",
        action: Action::OpenAssetClean,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Keep version…",
        action: Action::KeepVersion,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Last file",
        action: Action::LastBuffer,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "New document",
        action: Action::NewDocument,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Move…",
        action: Action::MoveFile,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Rename note…",
        action: Action::OpenRenameNote,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Duplicate note",
        action: Action::DuplicateNote,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // FINISH FILE: the emacsclient "server-edit" convention — save, notify any daemon
    // `--wait` client, and switch to the previously-open file. The emacs `C-x #`
    // default is retired; Cmd-W is its native slot now (P5 of the keybinding
    // idiom audit — awl's closest analogue to "close the document": non-
    // destructive under stray muscle memory, since it saves rather than closes
    // anything). NATIVE-ONLY: the daemon handoff it notifies has no web analog.
    // See `crate::daemon`. (Action stays `FinishBuffer`.)
    Command {
        name: "Finish file",
        action: Action::FinishBuffer,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Follow link",
        action: Action::FollowLink,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Switch theme…",
        action: Action::OpenThemeMenu,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Caret style…",
        action: Action::OpenCaretMenu,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Dictionary…",
        action: Action::OpenDictionaryMenu,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle spellcheck",
        action: Action::ToggleSpellcheck,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle caret style",
        action: Action::ToggleCaretMode,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle page mode",
        action: Action::TogglePageMode,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle writing nits",
        action: Action::ToggleWritingNits,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Widen page",
        action: Action::PageWider,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Narrow page",
        action: Action::PageNarrower,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Reset page width",
        action: Action::PageReset,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle debug",
        action: Action::ToggleDebug,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle outline",
        action: Action::ToggleOutline,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // FOLD SECTION: collapse/expand the markdown section under the caret (view state,
    // never file content). Default Cmd-. / C-c C-f; rebindable via config `[keys]`.
    Command {
        name: "Fold section",
        action: Action::ToggleFold,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Collapse other sections",
        action: Action::CollapseOtherSections,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle typewriter scroll",
        action: Action::ToggleTypewriter,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Toggle menu bar",
        action: Action::ToggleMenuBar,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "About",
        action: Action::About,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Credits",
        action: Action::OpenCredits,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Guide",
        action: Action::OpenGuide,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Lifetime stats",
        action: Action::LifetimeStats,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Writing streaks",
        action: Action::WritingStreaks,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    // LINE ENDINGS: toggle the active file's on-disk ending (LF <-> CRLF). No default
    // chord — the palette IS its entry point (a rare command, like Settings/About); a
    // real `Action` (`ConvertLineEndings`), independently rebindable via `[keys]`.
    Command {
        name: "Line endings…",
        action: Action::ConvertLineEndings,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // ALIGN TABLE: re-pad the GFM table under the caret so its `|` line up (source
    // alignment, never a drawn grid). No default chord — the palette IS its entry
    // point (like Settings/About); a real `Action`, independently rebindable.
    Command {
        name: "Align table",
        action: Action::AlignTable,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Insert Date",
        action: Action::InsertDate,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // REPORT A PROBLEM: compose a mailto: link to the maintainer, with the
    // newest local crash log's path attached-by-name if one exists (never its
    // content — the crash-visibility privacy law). No default chord — the
    // palette IS its entry point (like Settings/About/Align table); a real
    // `Action`, independently rebindable via `[keys]`. `native_only: false` —
    // available on the web build too (the mailto composition is pure and
    // platform-agnostic; only the crash-log path lookup is native-only). See
    // `crashlog.rs`.
    Command {
        name: "Report a Problem",
        action: Action::ReportProblem,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Download file",
        action: Action::DownloadFile,
        native: "",
        emacs: "",
        native_only: false,
        web_only: true,
    },
    // CHECK FOR UPDATES: never a network fetch — records a LOCAL "last checked"
    // marker (best-effort, `updates::record_checked`) then hands off to the OS
    // browser at the site's own `/check?v=…` page, which does the actual version
    // comparison against its own `version.json` (see `updates.rs`). No default
    // chord — the palette IS its entry point (like Report a Problem/About). Uses
    // the SAME `Effect::FollowLink`-style OS-handoff seam `App::follow_link`
    // already provides. `native_only: true` — the web build updates by
    // deploy/refresh, so "checking" is meaningless there.
    Command {
        name: "Check for Updates",
        action: Action::CheckForUpdates,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Blockquote",
        action: Action::ToggleBlockquote,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Bullet list",
        action: Action::ToggleBulletList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Numbered list",
        action: Action::ToggleNumberedList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Task list",
        action: Action::ToggleTaskList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Heading",
        action: Action::ToggleHeading,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Cycle heading",
        action: Action::HeadingCycle,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Code block",
        action: Action::ToggleCodeBlock,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Bold",
        action: Action::Bold,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Italic",
        action: Action::Italic,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Inline code",
        action: Action::InlineCode,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Highlight",
        action: Action::Highlight,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Strikethrough",
        action: Action::Strikethrough,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as Word…",
        action: Action::ExportWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as HTML…",
        action: Action::ExportHtml,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as PDF…",
        action: Action::ExportPdf,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Insert link…",
        action: Action::InsertLink,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Save",
        action: Action::Save,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Quit",
        action: Action::Quit,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Search forward",
        action: Action::SearchForward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Search backward",
        action: Action::SearchBackward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Find and replace…",
        action: Action::OpenReplace,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Undo",
        action: Action::Undo,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Redo",
        action: Action::Redo,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Copy",
        action: Action::CopyRegion,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Cut",
        action: Action::KillRegion,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Paste",
        action: Action::Yank,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Select all",
        action: Action::SelectAll,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Zoom in",
        action: Action::ZoomIn,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Zoom out",
        action: Action::ZoomOut,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Reset zoom",
        action: Action::ZoomReset,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // MOTION COMMANDS (user-decided 2026-07-10, superseding the original all-motions
    // exclusion — see the module doc): the curated NAVIGATION motions are catalog rows
    // so they show in Cmd-P + the Keybindings rebind menu and are REBINDABLE via
    // `[keys]`. The concrete ask this serves: reclaiming the retired Option-letter
    // word motion — `forward_word = ["M-Right", "M-f"]` / `backward_word =
    // ["M-Left", "M-b"]` — which macOS reserves for typing by DEFAULT (the platform
    // rule that retired the M-letter layer) but a config line may deliberately opt
    // back in. Each row shows its REAL default chord (both slots fire; a config
    // override is ADDITIVE); the emacs slots left empty by that retirement stay
    // empty for the user to fill — never re-shipped. Line start/end keep their
    // surviving bare-control second slots (C-a / C-e), now visible + teachable.
    Command {
        name: "Forward word",
        action: Action::ForwardWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Backward word",
        action: Action::BackwardWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Line start",
        action: Action::LineStart,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Line end",
        action: Action::LineEnd,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Document start",
        action: Action::BufferStart,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Document end",
        action: Action::BufferEnd,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Forward char",
        action: Action::ForwardChar,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Backward char",
        action: Action::BackwardChar,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Next line",
        action: Action::NextLine,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Previous line",
        action: Action::PreviousLine,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // WORD-DELETE, the mutating siblings of the word MOTIONS above — catalog rows
    // so `[keys]` can reach them (`delete_word_forward = "M-d"` reclaims the
    // classic emacs kill-word; `delete_word_backward = "M-Backspace"`). Both slots
    // are EMPTY by default: the SURVIVING default chords (⌥⌫ back, ⌥Delete / C-⌫ /
    // C-Delete forward) are dispatched by `keymap::resolve_named`'s static
    // NamedKey arms, NOT a catalog chord — the SAME split the plain char/line
    // motions above use (arrows fire from static arms; the catalog row exists only
    // to show in Cmd-P + be rebindable). The retired M-letter emacs slot stays
    // empty for the user to fill, never re-shipped (the word-motion precedent).
    Command {
        name: "Delete word forward",
        action: Action::DeleteWordForward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Delete word backward",
        action: Action::DeleteWordBackward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Settings…",
        action: Action::OpenSettingsMenu,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Keybindings…",
        action: Action::OpenKeybindings,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
];
