use super::cjk::{
    CJK_GOTHIC, CJK_JA_KLEE, CJK_JA_SHIPPORI, CJK_JA_ZENMARU, CJK_KO, CJK_KO_SERIF, CJK_MINCHO,
    CJK_ZH_HANS_KLEE, CJK_ZH_HANS_SANS, CJK_ZH_HANS_SERIF, CJK_ZH_HANT,
};
use super::color::Srgb;
use super::ground::{Background, LavaEdge, Weave};
use super::model::{
    AmbientStyle, Backdrop, CardAnchor, CardShape, CardTexture, CaretBlockStyle, ChipVariant,
    ChromeFace, DecorativeWash, Elevation, FacetStyle, FoldAfford, Frost, HighlightTexture,
    IconCursor, IconGround, ImageReveal, ListStyle, MotionJuice, PageFrame, PaneSplit,
    PlacardCorner, PlacardInk, RenderCaps, RoleOverrides, SPELL_UNDERLINE_GAP_DEFAULT,
    SelectionStyle, Theme, ThemeTags, TitleStyle, WashOverride,
};
use super::ornament::{
    BULLET_SCALE_GARAMOND, BULLET_SCALE_ORNAMENT, BULLET_SCALE_PLAIN, BULLETS_PLAIN,
    LIST_INDENT_SCALE_PLAIN, LIST_INDENT_SCALE_WIDE, ORNAMENT_GARAMOND, ORNAMENT_JUNICODE,
    ORNAMENT_MARKS, ORNAMENT_SCALE_FLEURON, ORNAMENT_SCALE_GEOMETRIC, ORNAMENT_SCALE_ORNATE,
    Ornaments,
};
const POSTER_BARS: ListStyle = ListStyle::Bars {
    radius: 6.0,
    gap: 10.0,
    grow_px: 24.0,
    extent: super::model::BarExtent::HugLabel,
    coverage: super::model::BarCoverage::All,
};
pub const GUMTREE: Theme = Theme {
    name: "Gumtree",
    dark: false,
    base_100: Srgb::rgb(0xE4, 0xF8, 0xE2),
    base_200: Srgb::rgb(0xCF, 0xF3, 0xCC),
    base_300: Srgb::rgb(0xB7, 0xEF, 0xB4),
    base_content: Srgb::rgb(0x16, 0x24, 0x1A),
    muted: Srgb::rgb(0x5A, 0x6B, 0x57),
    faint: Srgb::rgb(0x91, 0xA3, 0x8F),
    primary: Srgb::rgb(0xDA, 0x52, 0x5D),
    primary_content: Srgb::rgb(0xFB, 0xEC, 0xEC),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0x88, 0x8F, 0x5D, 0x52),
    background: Background::Zigzag {
        from: Srgb::rgb(0xE4, 0xF8, 0xE2),
        to: Srgb::rgb(0xCF, 0xF3, 0xCC),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0xB7, 0xEF, 0xB4),
        period_px: 170.0,
        amplitude_px: 60.0,
        angle: 0.26,
        density: 0.40,
        banded: false,
    },
    font: "Literata",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_JA_SHIPPORI,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('\u{E67D}', '\u{E270}', '\u{E68A}'),
    ornament_face: ORNAMENT_JUNICODE,
    ornament_scale: ORNAMENT_SCALE_ORNATE,
    bullets: ('❧', '☙', '❦'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Day"),
        register: None,
        voice: Some("Literary"),
        temperature: Some("Cool"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        ..RenderCaps::DEFAULT
    },
};
pub const POTOROO: Theme = Theme {
    name: "Potoroo",
    dark: true,
    base_100: Srgb::rgb(0x1F, 0x04, 0x00),
    base_200: Srgb::rgb(0x31, 0x05, 0x00),
    base_300: Srgb::rgb(0x56, 0x28, 0x00),
    base_content: Srgb::rgb(0xF0, 0xE6, 0xDE),
    muted: Srgb::rgb(0x9C, 0x85, 0x76),
    faint: Srgb::rgb(0x75, 0x5D, 0x51),
    primary: Srgb::rgb(0xFE, 0xAF, 0x69),
    primary_content: Srgb::rgb(0x2A, 0x14, 0x02),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0x7E, 0xB4, 0x7C, 0x52),
    background: Background::Stripes {
        from: Srgb::rgb(0x1F, 0x04, 0x00),
        to: Srgb::rgb(0x56, 0x28, 0x00),
        band: Srgb::rgb(0x6B, 0x3A, 0x12),
        angle: 0.6,
    },
    font: "Monaspace Xenon",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✶', '✦', '◆'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Dusk"),
        register: Some("Humble"),
        voice: Some("Technical"),
        temperature: Some("Warm"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Recessed,
        ..RenderCaps::DEFAULT
    },
};
pub const BILBY: Theme = Theme {
    name: "Bilby",
    dark: false,
    base_100: Srgb::rgb(0xFF, 0xF7, 0xEF),
    base_200: Srgb::rgb(0xFB, 0xED, 0xE6),
    base_300: Srgb::rgb(0xF3, 0xE1, 0xD6),
    base_content: Srgb::rgb(0x26, 0x20, 0x38),
    muted: Srgb::rgb(0x6B, 0x65, 0x7A),
    faint: Srgb::rgb(0xA7, 0x9D, 0xB6),
    primary: Srgb::rgb(0xBC, 0x7E, 0x16),
    primary_content: Srgb::rgb(0xFD, 0xF4, 0xE2),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0x8F, 0x7B, 0xB8, 0x52),
    background: Background::Gradient {
        from: Srgb::rgb(0xFB, 0xED, 0xE6),
        to: Srgb::rgb(0xF3, 0xE1, 0xD6),
        dir: (0.0, 1.0),
    },
    font: "Newsreader 16pt 16pt",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_JA_SHIPPORI,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('❧', '☙', '❦'),
    ornament_face: ORNAMENT_GARAMOND,
    ornament_scale: ORNAMENT_SCALE_FLEURON,
    bullets: ('❧', '❦', '☙'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Dawn"),
        register: Some("Refined"),
        voice: None,
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        spell_underline_gap: SPELL_UNDERLINE_GAP_DEFAULT - 2.0,
        ..RenderCaps::DEFAULT
    },
};
pub const SALTPAN: Theme = Theme {
    name: "Saltpan",
    dark: false,
    base_100: Srgb::rgb(0xFD, 0xF7, 0xE2),
    base_200: Srgb::rgb(0xFB, 0xF3, 0xDE),
    base_300: Srgb::rgb(0xF2, 0xE6, 0xC7),
    base_content: Srgb::rgb(0x24, 0x1D, 0x12),
    muted: Srgb::rgb(0x7A, 0x6E, 0x55),
    faint: Srgb::rgb(0xAB, 0xA3, 0x8F),
    primary: Srgb::rgb(0x8D, 0x59, 0x25),
    primary_content: Srgb::rgb(0xFB, 0xF1, 0xE6),
    error: Srgb::rgb(0xB5, 0x45, 0x2B),
    selection: Srgb::rgba(0xA5, 0x86, 0x50, 0x52),
    background: Background::Pinstripe {
        from: Srgb::rgb(0xFB, 0xF3, 0xDE),
        to: Srgb::rgb(0xF2, 0xE6, 0xC7),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0xD9, 0xC7, 0x9B),
    },
    font: "Fraunces 9pt",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_MINCHO,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('\u{F01B}', '\u{F01D}', '\u{F01E}'),
    ornament_face: ORNAMENT_JUNICODE,
    ornament_scale: ORNAMENT_SCALE_ORNATE,
    bullets: ('❦', '❧', '☙'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Dawn"),
        register: Some("Refined"),
        voice: None,
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        ..RenderCaps::DEFAULT
    },
};
pub const QUOKKA: Theme = Theme {
    name: "Quokka",
    dark: false,
    base_100: Srgb::rgb(0xFF, 0xEA, 0xDD),
    base_200: Srgb::rgb(0xFF, 0xDF, 0xCF),
    base_300: Srgb::rgb(0xFF, 0xD2, 0xBD),
    base_content: Srgb::rgb(0x2B, 0x18, 0x10),
    muted: Srgb::rgb(0x8A, 0x64, 0x53),
    faint: Srgb::rgb(0xB4, 0x94, 0x85),
    primary: Srgb::rgb(0x07, 0x70, 0x73),
    primary_content: Srgb::rgb(0xE6, 0xF6, 0xF6),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0xBB, 0x80, 0x20, 0x52),
    background: Background::Zigzag {
        from: Srgb::rgb(0xFF, 0xDF, 0xCF),
        to: Srgb::rgb(0xFF, 0xD2, 0xBD),
        dir: (0.7, 0.7),
        tint: Srgb::rgb(0xE0, 0xAE, 0x92),
        period_px: 100.0,
        amplitude_px: 24.0,
        angle: 0.0,
        density: 0.60,
        banded: true,
    },
    font: "Sour Gummy",
    mono: "IBM Plex Mono",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_JA_KLEE,
    zh_hans: CJK_ZH_HANS_KLEE,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✿', '❀', '✽'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Dawn"),
        register: Some("Everyday"),
        voice: Some("Modern"),
        temperature: Some("Warm"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        card_texture: CardTexture::HalftoneDots {
            angle_deg: 18.0,
            cell_px: 8.0,
            density: 0.30,
        },
        card_shape: CardShape::Chamfered { cut_px: 11.0 },
        ..RenderCaps::DEFAULT
    },
};
pub const BOMBORA: Theme = Theme {
    name: "Bombora",
    dark: true,
    base_100: Srgb::rgb(0x15, 0x0A, 0x2C),
    base_200: Srgb::rgb(0x24, 0x15, 0x40),
    base_300: Srgb::rgb(0x3C, 0x36, 0x54),
    base_content: Srgb::rgb(0xEC, 0xE8, 0xF2),
    muted: Srgb::rgb(0x8A, 0x7F, 0xA8),
    faint: Srgb::rgb(0x53, 0x48, 0x6E),
    primary: Srgb::rgb(0xC5, 0x3C, 0x69),
    primary_content: Srgb::rgb(0x2A, 0x0A, 0x16),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0x60, 0x50, 0xA8, 0x60),
    background: Background::Waves {
        tones: [
            Srgb::rgb(0x15, 0x0A, 0x2C),
            Srgb::rgb(0x24, 0x15, 0x40),
            Srgb::rgb(0x3C, 0x36, 0x54),
        ],
    },
    font: "EB Garamond",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_JA_SHIPPORI,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('☙', '❧', '❦'),
    ornament_face: ORNAMENT_GARAMOND,
    ornament_scale: ORNAMENT_SCALE_FLEURON,
    bullets: ('☞', '❧', '❦'),
    bullet_scale: BULLET_SCALE_GARAMOND,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Night"),
        register: Some("Refined"),
        voice: Some("Literary"),
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps::DEFAULT,
};

pub const MULGA: Theme = Theme {
    name: "Mulga",
    dark: true,
    base_100: Srgb::rgb(0x16, 0x1F, 0x0F),
    base_200: Srgb::rgb(0x1E, 0x29, 0x16),
    base_300: Srgb::rgb(0x3E, 0x4A, 0x31),
    base_content: Srgb::rgb(0xEC, 0xEA, 0xE0),
    muted: Srgb::rgb(0x8A, 0x8C, 0x78),
    faint: Srgb::rgb(0x51, 0x56, 0x47),
    primary: Srgb::rgb(0xDE, 0x8E, 0x7F),
    primary_content: Srgb::rgb(0x2A, 0x14, 0x10),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0xFF, 0xEF, 0xAE, 0x52),
    background: Background::Starfield {
        from: Srgb::rgb(0x16, 0x1F, 0x0F),
        to: Srgb::rgb(0x1E, 0x29, 0x16),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0x7C, 0x80, 0x68),
    },
    font: "Zilla Slab",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_MINCHO,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('⁑', '⁂', '❦'),
    ornament_face: ORNAMENT_JUNICODE,
    ornament_scale: ORNAMENT_SCALE_ORNATE,
    bullets: ('☙', '❦', '❧'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: None,
        register: Some("Everyday"),
        voice: None,
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps::DEFAULT,
};

pub const TAWNY: Theme = Theme {
    name: "Tawny",
    dark: true,
    base_100: Srgb::rgb(0x16, 0x18, 0x1D),
    base_200: Srgb::rgb(0x20, 0x22, 0x28),
    base_300: Srgb::rgb(0x2A, 0x2D, 0x34),
    base_content: Srgb::rgb(0xE6, 0xE6, 0xE6),
    muted: Srgb::rgb(0x8B, 0x91, 0x9D),
    faint: Srgb::rgb(0x4E, 0x52, 0x5A),
    primary: Srgb::rgb(0xFF, 0xC0, 0x5E),
    primary_content: Srgb::rgb(0x26, 0x1A, 0x08),
    error: Srgb::rgb(0xE5, 0x4B, 0x4B),
    selection: Srgb::rgba(0x3A, 0x6F, 0xD8, 0x52),
    background: Background::Dots {
        from: Srgb::rgb(0x16, 0x18, 0x1D),
        to: Srgb::rgb(0x20, 0x22, 0x28),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0x2C, 0x2F, 0x37),
        edge: false,
    },
    font: "IBM Plex Mono",
    mono: "IBM Plex Mono",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✦', '✷', '◈'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: None,
        register: Some("Humble"),
        voice: None,
        temperature: Some("Neutral"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps::DEFAULT,
};

pub const MOPOKE: Theme = Theme {
    name: "Mopoke",
    dark: true,
    base_100: Srgb::rgb(0x1B, 0x18, 0x14),
    base_200: Srgb::rgb(0x25, 0x21, 0x1B),
    base_300: Srgb::rgb(0x31, 0x2B, 0x22),
    base_content: Srgb::rgb(0xE8, 0xE4, 0xDC),
    muted: Srgb::rgb(0x97, 0x8C, 0x7E),
    faint: Srgb::rgb(0x57, 0x50, 0x47),
    primary: Srgb::rgb(0xF5, 0x6E, 0x3D),
    primary_content: Srgb::rgb(0x26, 0x1A, 0x08),
    error: Srgb::rgb(0xE5, 0x4B, 0x4B),
    selection: Srgb::rgba(0x7B, 0x39, 0xC6, 0x52),
    background: Background::Dots {
        from: Srgb::rgb(0x1B, 0x18, 0x14),
        to: Srgb::rgb(0x25, 0x21, 0x1B),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0x33, 0x2D, 0x24),
        edge: false,
    },
    font: "Bitter",
    mono: "IBM Plex Mono",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_JA_KLEE,
    zh_hans: CJK_ZH_HANS_KLEE,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('\u{E670}', '\u{F011}', '\u{F014}'),
    ornament_face: ORNAMENT_JUNICODE,
    ornament_scale: ORNAMENT_SCALE_ORNATE,
    bullets: ('\u{E670}', '\u{EF92}', '\u{E67D}'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Dusk"),
        register: Some("Humble"),
        voice: None,
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps::DEFAULT,
};

pub const BOWERBIRD: Theme = Theme {
    name: "Bowerbird",
    dark: true,
    base_100: Srgb::rgb(0x0C, 0x14, 0x26),
    base_200: Srgb::rgb(0x13, 0x1D, 0x33),
    base_300: Srgb::rgb(0x1F, 0x2C, 0x49),
    base_content: Srgb::rgb(0xE7, 0xEA, 0xF2),
    muted: Srgb::rgb(0x80, 0x89, 0xA0),
    faint: Srgb::rgb(0x46, 0x4E, 0x63),
    primary: Srgb::rgb(0xF5, 0xA7, 0x42),
    primary_content: Srgb::rgb(0x2A, 0x1B, 0x06),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0x3D, 0x6B, 0xC4, 0x52),
    background: Background::Organic {
        tones: [
            Srgb::rgb(0x0C, 0x14, 0x26),
            Srgb::rgb(0x13, 0x1D, 0x33),
            Srgb::rgb(0x1F, 0x2C, 0x49),
        ],
        scale_px: 156.0,
        density: 0.46,
    },
    font: "IBM Plex Sans",
    mono: "JetBrains Mono",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_JA_ZENMARU,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('❂', '✴', '◈'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Night"),
        register: Some("Everyday"),
        voice: Some("Modern"),
        temperature: Some("Cool"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps::DEFAULT,
};

pub const CURRAWONG: Theme = Theme {
    name: "Currawong",
    dark: true,
    base_100: Srgb::rgb(0x06, 0x06, 0x07),
    base_200: Srgb::rgb(0x0E, 0x0F, 0x11),
    base_300: Srgb::rgb(0x1C, 0x1E, 0x22),
    base_content: Srgb::rgb(0xED, 0xEE, 0xF0),
    muted: Srgb::rgb(0x88, 0x8C, 0x94),
    faint: Srgb::rgb(0x44, 0x46, 0x4B),
    primary: Srgb::rgb(0xF4, 0xC5, 0x34),
    primary_content: Srgb::rgb(0x1E, 0x1A, 0x06),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0x3E, 0x5C, 0x8A, 0x52),
    background: Background::Gradient {
        from: Srgb::rgb(0x06, 0x06, 0x07),
        to: Srgb::rgb(0x0E, 0x0F, 0x11),
        dir: (0.0, 1.0),
    },
    font: "Iosevka",
    mono: "Iosevka",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✷', '✴', '⬥'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Night"),
        register: None,
        voice: Some("Technical"),
        temperature: Some("Neutral"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        card_anchor: CardAnchor::TopLeft,
        ambient: AmbientStyle::Stars {
            tint: Srgb::rgb(0x9B, 0xB0, 0xD2),
            cell_px: 34.0,
            density: 0.30,
            size_px: 2.6,
            peak: 0.5,
            floor: 0.18,
        },
        ..RenderCaps::DEFAULT
    },
};

pub const MANGROVE: Theme = Theme {
    name: "Mangrove",
    dark: true,
    base_100: Srgb::rgb(0x11, 0x27, 0x23),
    base_200: Srgb::rgb(0x18, 0x34, 0x2E),
    base_300: Srgb::rgb(0x26, 0x43, 0x3B),
    base_content: Srgb::rgb(0xD9, 0xE6, 0xE1),
    muted: Srgb::rgb(0x6F, 0x8A, 0x83),
    faint: Srgb::rgb(0x41, 0x55, 0x51),
    primary: Srgb::rgb(0xF2, 0xA6, 0x5C),
    primary_content: Srgb::rgb(0x2A, 0x18, 0x04),
    error: Srgb::rgb(0xFF, 0x6B, 0x5C),
    selection: Srgb::rgba(0x40, 0xA8, 0x9E, 0x60),
    background: Background::Lava {
        ground: Srgb::rgb(0x11, 0x27, 0x23),
        blob_lo: Srgb::rgb(0x17, 0x23, 0x2B),
        blob_hi: Srgb::rgb(0x22, 0x3C, 0x4F),
        edge: LavaEdge::Glow,
        dithered: true,
    },
    font: "JetBrains Mono",
    mono: "JetBrains Mono",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('❖', '◈', '⬥'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: None,
        register: None,
        voice: Some("Technical"),
        temperature: Some("Cool"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::Auto,
            scale: 3.0,
            ink: PlacardInk::Stipple,
        },
        card_anchor: CardAnchor::TopRight,
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::Bracket),
        fold_afford: FoldAfford {
            chevron_lift: 0.60,
            tail_lift: 0.75,
        },
        ..RenderCaps::DEFAULT
    },
};

pub const GALAH: Theme = Theme {
    name: "Galah",
    dark: false,
    base_100: Srgb::rgb(0xFC, 0xEE, 0xF1),
    base_200: Srgb::rgb(0xF8, 0xE0, 0xE6),
    base_300: Srgb::rgb(0xF1, 0xCF, 0xD9),
    base_content: Srgb::rgb(0x2A, 0x17, 0x1D),
    muted: Srgb::rgb(0x7C, 0x60, 0x68),
    faint: Srgb::rgb(0xA9, 0x92, 0x98),
    primary: Srgb::rgb(0xB2, 0x3A, 0x60),
    primary_content: Srgb::rgb(0xFB, 0xEA, 0xEE),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0x9A, 0x6B, 0x86, 0x52),
    background: Background::Gradient {
        from: Srgb::rgb(0xF8, 0xE0, 0xE6),
        to: Srgb::rgb(0xF1, 0xCF, 0xD9),
        dir: (0.7, 0.7),
    },
    font: "Figtree",
    mono: "IBM Plex Mono",
    icon_cursor: IconCursor::Narrow,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_JA_ZENMARU,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('❁', '❂', '✿'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Dawn"),
        register: None,
        voice: Some("Modern"),
        temperature: Some("Warm"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::Auto,
            scale: 3.0,
            ink: PlacardInk::Ghost,
        },
        card_anchor: CardAnchor::TopLeft,
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::Hairline),
        ..RenderCaps::DEFAULT
    },
};

pub const MAGPIE: Theme = Theme {
    name: "Magpie",
    dark: false,
    base_100: Srgb::rgb(0xFB, 0xFB, 0xFA),
    base_200: Srgb::rgb(0xF1, 0xF1, 0xEF),
    base_300: Srgb::rgb(0xE4, 0xE4, 0xE1),
    base_content: Srgb::rgb(0x11, 0x13, 0x17),
    muted: Srgb::rgb(0x6C, 0x70, 0x77),
    faint: Srgb::rgb(0x9F, 0xA2, 0xA6),
    primary: Srgb::rgb(0xDB, 0x5A, 0x2B),
    primary_content: Srgb::rgb(0xFB, 0xEF, 0xE9),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0x46, 0x61, 0x8F, 0x52),
    background: Background::Pinstripe {
        from: Srgb::rgb(0xF1, 0xF1, 0xEF),
        to: Srgb::rgb(0xE4, 0xE4, 0xE1),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0xC9, 0xC9, 0xC5),
    },
    font: "Bitter",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: false,
    cjk: CJK_MINCHO,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    ornaments: Ornaments::of('\u{EF90}', '\u{EF98}', '\u{EF9A}'),
    ornament_face: ORNAMENT_JUNICODE,
    ornament_scale: ORNAMENT_SCALE_ORNATE,
    bullets: ('❦', '☙', '❧'),
    bullet_scale: BULLET_SCALE_ORNAMENT,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Day"),
        register: None,
        voice: Some("Literary"),
        temperature: Some("Neutral"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::Auto,
            scale: 3.0,
            ink: PlacardInk::Ghost,
        },
        card_anchor: CardAnchor::TopLeft,
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::Underline),
        ..RenderCaps::DEFAULT
    },
};

pub const BROLGA: Theme = Theme {
    name: "Brolga",
    dark: false,
    base_100: Srgb::rgb(0xE9, 0xEF, 0xFB),
    base_200: Srgb::rgb(0xDC, 0xE6, 0xF8),
    base_300: Srgb::rgb(0xC7, 0xD7, 0xF2),
    base_content: Srgb::rgb(0x1B, 0x24, 0x36),
    muted: Srgb::rgb(0x58, 0x63, 0x7A),
    faint: Srgb::rgb(0x99, 0xA3, 0xB6),
    primary: Srgb::rgb(0xD7, 0x5B, 0x41),
    primary_content: Srgb::rgb(0xFC, 0xEE, 0xEA),
    error: Srgb::rgb(0xC0, 0x39, 0x2B),
    selection: Srgb::rgba(0x35, 0x57, 0xA0, 0x60),
    background: Background::Gradient {
        from: Srgb::rgb(0xDC, 0xE6, 0xF8),
        to: Srgb::rgb(0xC7, 0xD7, 0xF2),
        dir: (0.0, 1.0),
    },
    font: "IBM Plex Sans",
    mono: "IBM Plex Mono",
    icon_cursor: IconCursor::Pill,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✧', '✴', '⬥'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Day"),
        register: None,
        voice: None,
        temperature: Some("Cool"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        ..RenderCaps::DEFAULT
    },
};

pub const WAGTAIL: Theme = Theme {
    name: "Wagtail",
    dark: true,
    base_100: Srgb::rgb(0x00, 0x00, 0x00),
    base_200: Srgb::rgb(0x00, 0x00, 0x00),
    base_300: Srgb::rgb(0x00, 0x00, 0x00),
    base_content: Srgb::rgb(0xFF, 0xFF, 0xFF),
    muted: Srgb::rgb(0xFF, 0xFF, 0xFF),
    faint: Srgb::rgb(0xFF, 0xFF, 0xFF),
    primary: Srgb::rgb(0xFF, 0xFF, 0xFF),
    primary_content: Srgb::rgb(0x00, 0x00, 0x00),
    error: Srgb::rgb(0xFF, 0xFF, 0xFF),
    selection: Srgb::rgba(0xFF, 0xFF, 0xFF, 0xFF),
    background: Background::Gradient {
        from: Srgb::rgb(0x00, 0x00, 0x00),
        to: Srgb::rgb(0x00, 0x00, 0x00),
        dir: (0.0, 1.0),
    },
    font: "JetBrains Mono",
    mono: "JetBrains Mono",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✧', '⭑', '❡'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Dusk"),
        register: None,
        voice: None,
        temperature: None,
    },
    role_overrides: RoleOverrides {
        def_fg: Some(Srgb::rgb(0xFF, 0xFF, 0xFF)),
        const_fg: Some(Srgb::rgb(0xFF, 0xFF, 0xFF)),
        str_fg: Some(Srgb::rgb(0xFF, 0xFF, 0xFF)),
        comment_wash: WashOverride::Off,
        str_wash: WashOverride::Off,
    },
    render_caps: RenderCaps {
        selection_style: SelectionStyle::InverseVideo,
        caret_block_style: CaretBlockStyle::InverseVideo,
        backdrop: Backdrop::Flat,
        elevation: Elevation::Bordered,
        decorative_wash: DecorativeWash::Off,
        image_reveal: ImageReveal::Opaque,
        highlight_texture: HighlightTexture::Stipple {
            color: Srgb::rgb(0xFF, 0xFF, 0xFF),
            density: crate::render::dither::WAGTAIL_HIGHLIGHT_DITHER_DENSITY,
        },
        title_style: TitleStyle::InlinePrefix,
        page_frame: PageFrame::Line { weight_px: 2.0 },
        card_anchor: CardAnchor::TopLeft,
        chrome_face: ChromeFace::Body,
        motion: MotionJuice::CALM,
        list_style: ListStyle::Pane,
        facet_style: FacetStyle::Text,
        pane_split: PaneSplit::Split,
        ambient: AmbientStyle::None,
        spell_underline_gap: SPELL_UNDERLINE_GAP_DEFAULT,
        frost: Frost::DEFAULT,
        fold_afford: FoldAfford::DEFAULT,
        card_texture: CardTexture::DEFAULT,
        card_shape: CardShape::DEFAULT,
    },
};

pub const FIRETAIL: Theme = Theme {
    name: "Firetail",
    dark: true,
    base_100: Srgb::rgb(0x17, 0x09, 0x0C),
    base_200: Srgb::rgb(0x24, 0x0D, 0x12),
    base_300: Srgb::rgb(0x52, 0x16, 0x29),
    base_content: Srgb::rgb(0xEF, 0xE5, 0xE2),
    muted: Srgb::rgb(0x9F, 0x7E, 0x7C),
    faint: Srgb::rgb(0x69, 0x48, 0x4A),
    primary: Srgb::rgb(0xF2, 0xB1, 0x40),
    primary_content: Srgb::rgb(0x23, 0x14, 0x05),
    error: Srgb::rgb(0xE6, 0x4E, 0x48),
    selection: Srgb::rgba(0xB6, 0x5A, 0x6E, 0x60),
    background: Background::Lava {
        ground: Srgb::rgb(0x17, 0x09, 0x0C),
        blob_lo: Srgb::rgb(0x24, 0x0C, 0x14),
        blob_hi: Srgb::rgb(0x52, 0x18, 0x2C),
        edge: LavaEdge::Glow,
        dithered: false,
    },
    font: "Monaspace Xenon",
    mono: "Monaspace Xenon",
    // Item 121: the poster silhouette moved off the pill; the ground stays
    // the inert base_100 default pending the user's A/B/C ground pick.
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('✷', '✶', '✦'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: None,
        register: None,
        voice: None,
        temperature: Some("Warm"),
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::BL,
            scale: 4.5,
            ink: PlacardInk::Bold,
        },
        card_anchor: CardAnchor::TopLeft,
        chrome_face: ChromeFace::Named("Archivo Black"),
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::FilledActive),
        fold_afford: FoldAfford {
            chevron_lift: 0.0,
            tail_lift: 0.40,
        },
        ..RenderCaps::DEFAULT
    },
};

pub const CASSOWARY: Theme = Theme {
    name: "Cassowary",
    dark: true,
    base_100: Srgb::rgb(0x05, 0x05, 0x06),
    base_200: Srgb::rgb(0x0B, 0x0C, 0x0D),
    base_300: Srgb::rgb(0x14, 0x2C, 0x1E),
    base_content: Srgb::rgb(0xA8, 0xEC, 0xBE),
    muted: Srgb::rgb(0x5C, 0x9E, 0x70),
    faint: Srgb::rgb(0x37, 0x63, 0x4A),
    primary: Srgb::rgb(0xA8, 0xEC, 0xBE),
    primary_content: Srgb::rgb(0x05, 0x05, 0x06),
    error: Srgb::rgb(0xFF, 0x44, 0x36),
    selection: Srgb::rgba(0xD2, 0x45, 0x5F, 0x70),
    background: Background::Pinstripe {
        from: Srgb::rgb(0x05, 0x05, 0x06),
        to: Srgb::rgb(0x0B, 0x0C, 0x0D),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0x1E, 0x4A, 0x32),
    },
    font: "Iosevka",
    mono: "Iosevka",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('◆', '✴', '◈'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Night"),
        register: None,
        voice: Some("Technical"),
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        caret_block_style: CaretBlockStyle::Filled,
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::Auto,
            scale: 3.0,
            ink: PlacardInk::Bold,
        },
        card_anchor: CardAnchor::TopRight,
        chrome_face: ChromeFace::Named("Archivo Black"),
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::Bracket),
        pane_split: PaneSplit::Unified,
        ..RenderCaps::DEFAULT
    },
};

#[allow(dead_code)] // gallery-only exploration; not in THEMES (see doc above).
pub const CASSOWARY_LIGHT: Theme = Theme {
    name: "Cassowary Light",
    dark: false,
    base_100: Srgb::rgb(0xEE, 0xF4, 0xF0),
    base_200: Srgb::rgb(0xE2, 0xEC, 0xE6),
    base_300: Srgb::rgb(0xD2, 0xE1, 0xD8),
    base_content: Srgb::rgb(0x16, 0x24, 0x1B),
    muted: Srgb::rgb(0x5A, 0x6E, 0x62),
    faint: Srgb::rgb(0x92, 0xA3, 0x98),
    primary: Srgb::rgb(0xD9, 0x79, 0x22),
    primary_content: Srgb::rgb(0xFB, 0xEF, 0xE2),
    error: Srgb::rgb(0xC2, 0x34, 0x29),
    selection: Srgb::rgba(0xC8, 0x36, 0x5E, 0x5E),
    background: Background::Pinstripe {
        from: Srgb::rgb(0xE2, 0xEC, 0xE6),
        to: Srgb::rgb(0xD2, 0xE1, 0xD8),
        dir: (0.0, 1.0),
        tint: Srgb::rgb(0xAF, 0xC6, 0xB8),
    },
    font: "Iosevka",
    mono: "Iosevka",
    icon_cursor: IconCursor::Block,
    icon_ground: IconGround::Base100,
    heading_bold: true,
    cjk: CJK_GOTHIC,
    zh_hans: CJK_ZH_HANS_SANS,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO,
    ornaments: Ornaments::of('◆', '✴', '◈'),
    ornament_face: ORNAMENT_MARKS,
    ornament_scale: ORNAMENT_SCALE_GEOMETRIC,
    bullets: BULLETS_PLAIN,
    bullet_scale: BULLET_SCALE_PLAIN,
    list_indent_scale: LIST_INDENT_SCALE_PLAIN,
    tags: ThemeTags {
        time: Some("Day"),
        register: None,
        voice: Some("Technical"),
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        title_style: TitleStyle::Placard {
            corner: PlacardCorner::Auto,
            scale: 3.0,
            ink: PlacardInk::Bold,
        },
        card_anchor: CardAnchor::TopLeft,
        chrome_face: ChromeFace::Named("Archivo Black"),
        elevation: Elevation::Bordered,
        list_style: POSTER_BARS,
        facet_style: FacetStyle::Chips(ChipVariant::Bracket),
        pane_split: PaneSplit::Unified,
        ..RenderCaps::DEFAULT
    },
};

/// PAPERBARK — the nineteenth world (item 158, graduated from item 133's
/// material study). Handmade paper in a daylit studio: nested deckled contours
/// gather around the writing page in cream and pale honey, the prose is deep
/// bark-brown, and the one vermilion caret is the only accent.
///
/// Its ground is the ONE production assignee of [`Background::Deckle`] — the
/// static handmade-paper field, dialled to [`Weave::Strata`]. The material
/// stays entirely in the margins: the page is flat, opaque `base_100`, and
/// nothing here moves (no ambient capability, so `has_ambient_tick` is false by
/// construction). TEMPERATURE IS UNTAGGED ON PURPOSE — the picker's Warm band
/// is already at `axis_coverage_ruler`'s curated cap of four; WORLDS.md says
/// why.
pub const PAPERBARK: Theme = Theme {
    name: "Paperbark",
    dark: false,
    base_100: Srgb::rgb(0xFF, 0xF8, 0xE9),
    base_200: Srgb::rgb(0xF8, 0xEC, 0xD1),
    base_300: Srgb::rgb(0xEB, 0xD8, 0xAE),
    base_content: Srgb::rgb(0x38, 0x25, 0x1A),
    muted: Srgb::rgb(0x80, 0x68, 0x50),
    faint: Srgb::rgb(0xB3, 0x9B, 0x7C),
    primary: Srgb::rgb(0xD8, 0x5A, 0x42),
    primary_content: Srgb::rgb(0xFF, 0xF6, 0xE9),
    error: Srgb::rgb(0xB9, 0x3A, 0x2E),
    selection: Srgb::rgba(0xC7, 0x7A, 0x4B, 0x52),
    background: Background::Deckle {
        ground: Srgb::rgb(0xF0, 0xDF, 0xBA),
        layer: Srgb::rgb(0xD8, 0xB7, 0x7A),
        deckle: Srgb::rgb(0x9F, 0x69, 0x37),
        weave: Weave::Strata,
        period_px: 94.0,
        wander_px: 13.0,
        density: 0.20,
    },
    font: "EB Garamond",
    mono: "Monaspace Xenon",
    icon_cursor: IconCursor::Block,
    heading_bold: false,
    cjk: CJK_JA_SHIPPORI,
    zh_hans: CJK_ZH_HANS_SERIF,
    zh_hant: CJK_ZH_HANT,
    ko: CJK_KO_SERIF,
    // The third and last EB Garamond fleuron permutation (Bilby ❧ ☙ ❦, Bombora
    // ☙ ❧ ❦); the face ships exactly these three, so the trio is a rotation.
    ornaments: Ornaments::of('❦', '❧', '☙'),
    ornament_face: ORNAMENT_GARAMOND,
    ornament_scale: ORNAMENT_SCALE_FLEURON,
    bullets: ('☙', '❦', '❧'),
    bullet_scale: BULLET_SCALE_GARAMOND,
    list_indent_scale: LIST_INDENT_SCALE_WIDE,
    tags: ThemeTags {
        time: Some("Day"),
        register: Some("Refined"),
        voice: Some("Literary"),
        temperature: None,
    },
    role_overrides: RoleOverrides::NONE,
    render_caps: RenderCaps {
        elevation: Elevation::Bordered,
        ..RenderCaps::DEFAULT
    },
};

pub const THEMES: [Theme; 19] = [
    TAWNY, MOPOKE, CURRAWONG, POTOROO, GUMTREE, BILBY, SALTPAN, QUOKKA, BOMBORA, BOWERBIRD, MULGA,
    MANGROVE, GALAH, MAGPIE, BROLGA, WAGTAIL, FIRETAIL, CASSOWARY, PAPERBARK,
];

const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

const fn world_index(name: &str) -> usize {
    let mut i = 0;
    while i < THEMES.len() {
        if str_eq(THEMES[i].name, name) {
            return i;
        }
        i += 1;
    }
    panic!("world_index: no world by that name")
}

pub const DEFAULT_THEME: usize = world_index("Saltpan");

pub fn world_names() -> Vec<&'static str> {
    THEMES.iter().map(|t| t.name).collect()
}
