use super::Command;
use crate::keymap::Action;

pub(super) static COMMANDS: &[Command] = &[
    Command {
        name: "Blockquote",
        action: Action::ToggleBlockquote,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Bullet list",
        action: Action::ToggleBulletList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Numbered list",
        action: Action::ToggleNumberedList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Task list",
        action: Action::ToggleTaskList,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Heading",
        action: Action::ToggleHeading,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Cycle heading",
        action: Action::HeadingCycle,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Code block",
        action: Action::ToggleCodeBlock,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Bold",
        action: Action::Bold,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Italic",
        action: Action::Italic,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Inline code",
        action: Action::InlineCode,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Highlight",
        action: Action::Highlight,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Strikethrough",
        action: Action::Strikethrough,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as Word…",
        action: Action::ExportWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as HTML…",
        action: Action::ExportHtml,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Export as PDF…",
        action: Action::ExportPdf,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Insert link…",
        action: Action::InsertLink,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Save",
        action: Action::Save,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Review the change",
        action: Action::ReviewChange,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Save your version",
        action: Action::ResolveKeepMine,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Use disk version",
        action: Action::ResolveTakeTheirs,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Quit",
        action: Action::Quit,
        native: "",
        emacs: "",
        native_only: true,
        web_only: false,
    },
    Command {
        name: "Search forward",
        action: Action::SearchForward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Search backward",
        action: Action::SearchBackward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Find and replace…",
        action: Action::OpenReplace,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Undo",
        action: Action::Undo,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Redo",
        action: Action::Redo,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Copy",
        action: Action::CopyRegion,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Cut",
        action: Action::KillRegion,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Paste",
        action: Action::Yank,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Select all",
        action: Action::SelectAll,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Zoom in",
        action: Action::ZoomIn,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Zoom out",
        action: Action::ZoomOut,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Reset zoom",
        action: Action::ZoomReset,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // MOTION COMMANDS (user-decided 2026-07-10, superseding the original all-motions
    // exclusion — see the module doc): the curated NAVIGATION motions are catalog rows
    // so they show in Cmd-P + the Keybindings rebind menu and are REBINDABLE via
    // `[keys]`. The concrete ask this serves: reclaiming the retired Option-letter
    // word motion — `forward_word = ["M-Right", "M-f"]` / `backward_word =
    // ["M-Left", "M-b"]` — which macOS reserves for typing by DEFAULT (the platform
    // rule that retired the M-letter layer) but a config line may deliberately opt
    // back in. Each row shows its REAL default chord (both slots fire; a config
    // override is ADDITIVE); the emacs slots left empty by that retirement stay
    // empty for the user to fill — never re-shipped. Line start/end keep their
    // surviving bare-control second slots (C-a / C-e), now visible + teachable.
    Command {
        name: "Forward word",
        action: Action::ForwardWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Backward word",
        action: Action::BackwardWord,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Line start",
        action: Action::LineStart,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Line end",
        action: Action::LineEnd,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Document start",
        action: Action::BufferStart,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Document end",
        action: Action::BufferEnd,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Forward char",
        action: Action::ForwardChar,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Backward char",
        action: Action::BackwardChar,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Next line",
        action: Action::NextLine,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Previous line",
        action: Action::PreviousLine,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    // WORD-DELETE, the mutating siblings of the word MOTIONS above — catalog rows
    // so `[keys]` can reach them (`delete_word_forward = "M-d"` reclaims the
    // classic emacs kill-word; `delete_word_backward = "M-Backspace"`). Both slots
    // are EMPTY by default: the SURVIVING default chords (⌥⌫ back, ⌥Delete / C-⌫ /
    // C-Delete forward) are dispatched by `keymap::resolve_named`'s static
    // NamedKey arms, NOT a catalog chord — the SAME split the plain char/line
    // motions above use (arrows fire from static arms; the catalog row exists only
    // to show in Cmd-P + be rebindable). The retired M-letter emacs slot stays
    // empty for the user to fill, never re-shipped (the word-motion precedent).
    Command {
        name: "Delete word forward",
        action: Action::DeleteWordForward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Delete word backward",
        action: Action::DeleteWordBackward,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Settings…",
        action: Action::OpenSettingsMenu,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
    Command {
        name: "Keybindings…",
        action: Action::OpenKeybindings,
        native: "",
        emacs: "",
        native_only: false,
        web_only: false,
    },
];
